### ISSUE TITLE
你好啊 下载下来运行就直接crash了

### ISSUE THREAD

**Issue by xingze0308** [ddrccw/CCRichTextEditor#1]
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/pfmrw/Library/Developer/CoreSimulator/Devices/79F19B63-46B1-440E-97E4-9630B7C9E1F6/data/Containers/Bundle/Application/1732A840-E893-460D-9984-6F1D423E2D83/CCRichTextEditor.app> (loaded)' with name 'CCRichTextEditorViewControllerr_iPhone''

**Comment by ddrccw** [comment]
@xingze0308 这个项目是很久以前实验性的项目，只是做了ipad版本

**Comment by xingze0308** [comment]
恩恩  最后才发现是2年以前的了...
